// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ipywdfnqttwipmgtzewn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlweXdkZm5xdHR3aXBtZ3R6ZXduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3MDc3NDgsImV4cCI6MjA2MTI4Mzc0OH0.dPQr8TqGY5u7VPPbKqDBeyzOfM6w_NZO4GBkpliyiAY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});